- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages
  apt: pkg={{item}} state=present
  with_items:
#######
#  CLI convenience
######
#    - byobu
    - mosh
#    - tmux
#    - tcl
    - vim
#    - zsh
#######   
#   Building source
######
    - build-essential
    - cmake
    - curl
    - gcc
    - git
    - libzmq3-dev
    - libncurses5-dev
    - liblzma-dev
    - libblas-dev    
    - libcurl4-openssl-dev    
    - pigz
#    - python-dev
    - python-pip
    - zip
    - zlib1g-dev
#######
#   Module management
######
    - lua5.2
    - liblua5.2-dev
    - lua-filesystem
    - lua-posix
#######
#   FS management
######
    - cifs-utils
